export const LIST_ACCOUNT = [
  {
    id: 1,
    full_name: "Nguyễn Phương Nhi",
    nickname: "_phuongnhi.22",
    avatar: "../public/images/_phuongnhi.22.jpeg",
    tick: true,
    followers: "795.3K",
    likes: "21.3M",
    following: "32",
    information_1: "Contact: Ms. Việt Mỹ 0974.28.21.21",
    information_2: "📩talents@senvangvn.com",
    information_3: "",
    information_4: "",
    link: "",
    videos: [
      "/public/videos/phuongnhi/Download.mp4",
      "/public/videos/phuongnhi/Download (1).mp4",
      "/public/videos/phuongnhi/Download (2).mp4",
      "/public/videos/phuongnhi/Download (3).mp4",
      "/public/videos/phuongnhi/Download (4).mp4",
      "/public/videos/phuongnhi/Download (5).mp4",
      "/public/videos/phuongnhi/Download (6).mp4",
      "/public/videos/phuongnhi/Download (7).mp4",
      "/public/videos/phuongnhi/Download (8).mp4",
      "/public/videos/phuongnhi/Download (9).mp4",
      "/public/videos/phuongnhi/Download (10).mp4",
      "/public/videos/phuongnhi/Download (11).mp4",
    ],
  },
  {
    id: 2,
    full_name: "CiiN",
    nickname: "cciinnn",
    avatar: "../public/images/cciinnn.jpeg",
    tick: true,
    followers: "10.4M",
    likes: "268.3M",
    following: "189",
    information_1: "KHÔNG ACC PHỤ",
    information_2: "KOL - DANCER",
    information_3: "FB: Bùi Thảo Ly (Sịn) - IG: l.ciin",
    information_4: "👇🏻",
    link: "beacons.ai/ciin",
    videos: [
      "/public/videos/ciin/Download.mp4",
      "/public/videos/ciin/Download (1).mp4",
      "/public/videos/ciin/Download (2).mp4",
      "/public/videos/ciin/Download (3).mp4",
      "/public/videos/ciin/Download (4).mp4",
      "/public/videos/ciin/Download (5).mp4",
      "/public/videos/ciin/Download (6).mp4",
      "/public/videos/ciin/Download (7).mp4",
    ],
  },
  {
    id: 3,
    full_name: "Lương Thuỳ Linh",
    nickname: "luongthuylinh_",
    avatar: "../public/images/luongthuylinh_.jpeg",
    tick: true,
    followers: "349.1K",
    likes: "11M",
    following: "0",
    information_1: "👑 Miss World VN 2019 👑",
    information_2: "📩: Talents@senvangvn.com",
    information_3: "📞: +84974282121 ( Mrs. Mỹ)",
    information_4: "",
    link: "youtube.com/@luongthuylinhoffic",
  },
  {
    id: 4,
    full_name: "Linh Tít 🐰💫",
    nickname: "embetit1",
    avatar: "../public/images/embetit1.jpeg",
    tick: false,
    followers: "461.9K",
    likes: "6.7M",
    following: "50",
    information_1: "CHỈ DUY NHẤT NICK NÀY, pls",
    information_2: "Link FB ở IG 🫶🏻",
    information_3: "Tui đã mua nên yên tâm nhé 👇🏻🛒🎀",
    information_4: "",
    link: "embetit1.passio.eco",
    videos: [
      "/public/videos/linhtit/Download.mp4",
      "/public/videos/linhtit/Download (1).mp4",
      "/public/videos/linhtit/Download (2).mp4",
      "/public/videos/linhtit/Download (3).mp4",
      "/public/videos/linhtit/Download (4).mp4",
      "/public/videos/linhtit/Download (5).mp4",
      "/public/videos/linhtit/Download (6).mp4",
      "/public/videos/linhtit/Download (7).mp4",
      "/public/videos/linhtit/Download (8).mp4",
      "/public/videos/linhtit/Download (9).mp4",
      "/public/videos/linhtit/Download (10).mp4",
      "/public/videos/linhtit/z.mp4",
    ],
  },
  {
    id: 5,
    full_name: "Mâyđeiii ❤️",
    nickname: "maydei.3010",
    avatar: "../public/images/maydei.jpeg",
    tick: false,
    followers: "625.3K",
    likes: "8.9M",
    following: "132",
    information_1: "CONTACT FOR WORK",
    information_2: "EMail: Aliee.lcdancestudio@gmail.com",
    information_3: "",
    information_4: "",
    link: "instabio.cc/3052603zISS2O",
  },
  {
    id: 6,
    full_name: "Lê Huyền Diệu",
    nickname: "lhdieu",
    avatar: "../public/images/lhd.jpeg",
    tick: true,
    followers: "2M",
    likes: "34M",
    following: "33",
    information_1: "📨 Inb for Work",
    information_2: "📞0971672036 ( Mss Thu )",
    information_3: "💌:Huyendieu1309@gmail.com",
    information_4: "",
    link: "lhdieuu.kol.eco",
  },
  {
    id: 7,
    full_name: "Zika_hila🧚🏿‍♀️",
    nickname: "zixinhdep",
    avatar: "../public/images/zixinhdep.jpeg",
    tick: false,
    followers: "2.4M",
    likes: "63.1M",
    following: "52",
    information_1: "Contact for work",
    information_2: "storm.zikahila@gmail.com",
    information_3: "0877 8484 01",
    information_4: "",
    link: "",
    videos: [
      "/public/videos/zika/Download.mp4",
      "/public/videos/zika/Download (1).mp4",
      "/public/videos/zika/Download (2).mp4",
      "/public/videos/zika/Download (3).mp4",
      "/public/videos/zika/Download (4).mp4",
      "/public/videos/zika/Download (5).mp4",
      "/public/videos/zika/Download (6).mp4",
      "/public/videos/zika/Download (7).mp4",
      "/public/videos/zika/Download (8).mp4",
      "/public/videos/zika/Download (9).mp4",
      "/public/videos/zika/Download (10).mp4",
      "/public/videos/zika/Download (11).mp4",
    ],
  },
  {
    id: 8,
    full_name: "đỗ hanutest thì đổi tên",
    nickname: "khongduocbeo",
    avatar: "../public/images/khongduocbeo.jpeg",
    tick: true,
    followers: "124",
    likes: "933",
    following: "218",
    information_1: "No bio yet.",
    information_2: "",
    information_3: "",
    information_4: "",
    link: "",
  },
  {
    id: 9,
    full_name: "Dũng Lại Lập Trình 🇦🇺🇻🇳",
    nickname: "dunglailaptrinh",
    avatar: "../public/images/dunglailaptrinh.jpeg",
    tick: false,
    followers: "158K",
    likes: "1.3M",
    following: "8",
    information_1: "Thủ khoa toán vào 10 | Á khoa chuyên toán Ams",
    information_2: "Đăng kí ôn luyện toán vào 10 👇",
    information_3: "",
    information_4: "",
    link: "dunglailaptrinh.com",
  },
  {
    id: 10,
    full_name: "Đỗ Thị Hà",
    nickname: "doha_20.07",
    avatar: "../public/images/doha_20.07.jpeg",
    tick: true,
    followers: "782.2K",
    likes: "23.1M",
    following: "51",
    information_1: "Hoa hậu Việt Nam 2020",
    information_2: "Top 13 Miss World 2021",
    information_3: "",
    information_4: "",
    link: "https://www.facebook.com/doha200701",
  },
  {
    id: 11,
    full_name: "Nguyễn Thúc Thuỳ Tiên",
    nickname: "missgrand2021.thuytien",
    avatar: "../public/images/missgrand2021.thuytien.jpeg",
    tick: true,
    followers: "3.9M",
    likes: "114.5M",
    following: "8",
    information_1: "👑 Miss Grand International 2021 👑",
    information_2: "Booking: Ms. Việt Mỹ 0974282121",
    information_3: "",
    information_4: "",
    link: "",
  },
  {
    id: 12,
    full_name: "thou đin khùm🇻🇳",
    nickname: "thouthou_vanila",
    avatar: "../public/images/thouthou_vanila.jpeg",
    tick: false,
    followers: "1.4M",
    likes: "26.3M",
    following: "30",
    information_1: "🔥ThouThou mãi cháy🔥",
    information_2: "CONTACT FOR WORK: thaocoxanh04@gmail.com",
    information_3: "Dance❤️‍🔥",
    information_4: "",
    link: "thouthou.passio.eco",
  },
  {
    id: 13,
    full_name: "Nguyễn Đan Phương❤️",
    nickname: "ndp_2002",
    avatar: "../public/images/ndp_2002.jpeg",
    tick: false,
    followers: "1.9M",
    likes: "55.2M",
    following: "55",
    information_1: "Đồ mình mặc mình có bán nhé nhắn qua 'Instagram'👈🏻",
    information_2: "📩 ndp2362002@gmail.com",
    information_3: "",
    information_4: "",
    link: "https://www.facebook.com/Duonggman?mibextid=LQQJ4d",
  },
  {
    id: 14,
    full_name: "Lan Nhi 🖤",
    nickname: "lannhibabyy",
    avatar: "../public/images/lannhibabyy.jpeg",
    tick: false,
    followers: "229.6K",
    likes: "3.7M",
    following: "9",
    information_1: "LIFESTYLE | FASHION | BEAUTY",
    information_2: "Booking:",
    information_3: "Mail: lannhi.booking@gmail.com",
    information_4: "",
    link: "https://www.facebook.com/lannhibaby308?mibextid=LQQJ4d",
  },
  {
    id: 15,
    full_name: "Hiển Hồ handsome number one in the World❤️",
    nickname: "hien_ho_102",
    avatar: "../public/images/hienho.jpeg",
    tick: true,
    followers: "23M",
    likes: "234M",
    following: "24",
    information_1: "No bio yet.",
    information_2: "",
    information_3: "",
    information_4: "",
    link: "https://www.facebook.com/hiendzvlone2303/",
  },
];
