export const LIST_VIDEO_HOME = [
  {
    id: 1,
    nick_name: "babie.ne",
    full_name: "🦋 BABY NÈ 🦋 flop nhiều quá",
    avatar: "../public/images/babie.ne.jpeg",
    content: "",
    hag_tag: "#xuhuong2023 #xuhuongtiktok #hoaqua",
    music:
      "Là Anh (Nguyễn Hoàng ft. Hải Nam Remix) [Short Version] - Exclusive Music & Phạm Lịch",
    video: "/public/videos/babie.mp4",
    likes: "58.4K",
    comments: "575",
    shares: "1109",
  },
  {
    id: 2,
    nick_name: "chikhang0311",
    full_name: "Chí Khang",
    avatar: "../public/images/chikhang0311.jpeg",
    content: "Thì không choa thoai",
    hag_tag: "#tiktokgiatri #xuhuong #dqn",
    music: "nhạc nền - CD03ᥫ᭡[WS]",
    video: "/public/videos/chikhang.mp4",
    likes: "134.9K",
    comments: "1866",
    shares: "842",
  },
  {
    id: 3,
    nick_name: "_phuongnhi.22",
    full_name: "Nguyễn Phương Nhi",
    avatar: "../public/images/_phuongnhi.22.jpeg",
    content: "Váy trắng liệu có làm mng lo lắng ?!! ",
    hag_tag: "#ahauphuongnhi #nguyenphuongnhi #phuongnhi #missworldvietnam",
    music: "nhạc nền - Nguyễn Phương Nhi",
    video: "/public/videos/phuongnhi.mp4",
    likes: "213.9K",
    comments: "728",
    shares: "502",
  },
  {
    id: 4,
    nick_name: "embetit1",
    full_name: "Linh Tít 🐰💫",
    avatar: "../public/images/embetit1.jpeg",
    content: "nhảy linh tinh z đó",
    hag_tag: "#dqn",
    music: "nhạc nền - Linh Tít 🐰💫",
    video: "/public/videos/linhtit.mp4",
    likes: "41.3K",
    comments: "140",
    shares: "99",
  },
  {
    id: 5,
    nick_name: "luongthuylinh_",
    full_name: "Lương Thuỳ Linh",
    avatar: "../public/images/luongthuylinh_.jpeg",
    content: "Alo alo",
    hag_tag: "#luongthuylinh #missworldvietnam",
    music: "nhạc nền - Lương Thuỳ Linh",
    video: "/public/videos/luongthuylinh.mp4",
    likes: "26.6K",
    comments: "140",
    shares: "23",
  },
  {
    id: 6,
    nick_name: "cciinnn",
    full_name: "CiiN",
    avatar: "../public/images/cciinnn.jpeg",
    content: "Love the song yaaaaaah 🖤💖",
    hag_tag: "#Jisoo #Jisoosolo #Flower #FlowerJisoo",
    music: "FLOWER - JISOO",
    video: "/public/videos/ciin.mp4",
    likes: "734.5K",
    comments: "3012",
    shares: "2303",
  },
  {
    id: 7,
    nick_name: "hoaa.hanassii",
    full_name: "Đào Lê Phương Hoa",
    avatar: "../public/images/hoaa.hanassii.jpeg",
    content: "Mình tên Hoa nên nhảy FLOWER hợp lý quá ròii 🌺",
    hag_tag: "#Jisoo #Jisoosolo #Flower #FlowerJisoo",
    music:
      "#JISOO_FLOWER #지수꽃 #FLOWERchallenge #JISOO #지수 #BLACKPINK #블랙핑크",
    video: "/public/videos/daolephuonghoa.mp4",
    likes: "2.8M",
    comments: "9152",
    shares: "100.1K",
  },
  {
    id: 8,
    nick_name: "asquarecrew",
    full_name: "ASquare Crew",
    avatar: "../public/images/asquarecrew.jpeg",
    content: "Jisoo Flower Dance with my Mom",
    hag_tag:
      "#momson #aayush #fyp #foryou #trend #viral #asquarecrew #jisoo #flowerdancechallenge #blackpink #aayushandabhay",
    music: "FLOWER - JISOO",
    video: "/public/videos/asqua.mp4",
    likes: "4.5M",
    comments: "23.1K",
    shares: "12.9K",
  },
  {
    id: 9,
    nick_name: "zixinhdep",
    full_name: "Zika_hila🧚🏿‍♀️",
    avatar: "../public/images/zixinhdep.jpeg",
    content: "Nghịch thì nhất em",
    hag_tag: "#stromick",
    music: "nhạc nền - Zika_hila🧚🏿‍♀️",
    video: "/public/videos/zikahila.mp4",
    likes: "95.9K",
    comments: "189",
    shares: "59",
  },
  {
    id: 10,
    nick_name: "zixinhdep",
    full_name: "Zika_hila🧚🏿‍♀️",
    avatar: "../public/images/zixinhdep.jpeg",
    content: "Lên ☝🏻",
    hag_tag: "#stromick",
    music: "nhạc nền - Anh Quan",
    video: "/public/videos/zika.mp4",
    likes: "575K",
    comments: "1906",
    shares: "398",
  },
  {
    id: 11,
    nick_name: "quankdivaobarr",
    full_name: "Quân K Đi Vào Bar 🕺🏻",
    avatar: "../public/images/quankdivaobarr.jpeg",
    content: "Hạ Cánh cùng cặp đôi Quân K-Air Đi Vào Bair",
    hag_tag: "#quankdivaobarr #hadalux #iconicglss #vtmgr @Quan _Air",
    music: "nhạc nền - Quân K Đi Vào Bar 🕺🏻",
    video: "/public/videos/quank.mp4",
    likes: "7085",
    comments: "43",
    shares: "3",
  },
  {
    id: 12,
    nick_name: "_clouddom",
    full_name: "Mâyy ☁️",
    avatar: "../public/images/_clouddom.jpeg",
    content: "Hai cô em chuẩn bị ứng tuyển làm thư ký chủ tịch 🫂 (dc: ? ) ",
    hag_tag: "#dqn #clouddom #tiktokdancevn",
    music: "Brandon Beal x Công Thành Remix - 𝐄𝐱𝐜𝐥𝐮𝐬𝐢𝐯𝐞 𝐌𝐮𝐬𝐢𝐜",
    video: "/public/videos/clound.mp4",
    likes: "82.9K",
    comments: "173",
    shares: "72",
  },
  {
    id: 13,
    nick_name: "vaan.ilu",
    full_name: "vaan.ilu",
    avatar: "../public/images/vaan.ilu.jpeg",
    content: "tìm một mảnh ghép của đôi ta🧚🏻‍♀️✨",
    hag_tag: "#CapCut",
    music: "nhạc nền - L",
    video: "/public/videos/vanIu.mp4",
    likes: "38.2K",
    comments: "136",
    shares: "94",
  },
  {
    id: 14,
    nick_name: "nhacnomusik",
    full_name: "𝑵𝒉𝒂𝒄 𝑵𝒐 𝑴𝒖𝑺𝒊𝒌 🌬️",
    avatar: "../public/images/nhacnomusik.jpeg",
    content: "Bậc Tình Yêu Lên ❤️‍🔥",
    hag_tag: "#lyrics #remix #foryou #fypシ #xuhuongtiktok #nhacnomusik",
    music: "Bật Tình Yêu Lên Remix - CUKAK",
    video: "/public/videos/nhacmusic.mp4",
    likes: "118.4K",
    comments: "303",
    shares: "1456",
  },
  {
    id: 15,
    nick_name: "sivsole97",
    full_name: "Dương Nguyễn",
    avatar: "../public/images/sivsole97.jpeg",
    content:
      "Biệt đội đổ nhớt tại đám cưới @Hungheo13 quẩy nhiệt quá @Đoàn Huy Hoàng",
    hag_tag: "#hoàngtửnhớt #thánhđổnhớt #dươngnhotsdl #sivsole97",
    music: "nhạc nền - Dương Nguyễn",
    video: "/public/videos/damcuoi.mp4",
    likes: "195.8K",
    comments: "1084",
    shares: "354",
  },
  {
    id: 16,
    nick_name: "tongplayhub",
    full_name: "Tòng Playhub",
    avatar: "../public/images/tongplayhub.jpeg",
    content: "Mùa thu không còn trong tâm trí em, nhưng anh thì còn",
    hag_tag:
      "#tong106thaithinh #tong #djmvinyl #djducmanh #remix #thucuoi #vitamintraiđẹp #xuhuong",
    music: "nhạc nền - Tòng Playhub",
    video: "/public/videos/tonghub.mp4",
    likes: "298.3K",
    comments: "3811",
    shares: "3803",
  },
  {
    id: 17,
    nick_name: "thuongthuongtotinh",
    full_name: "ở đây chỉ có Rap 🎧",
    avatar: "../public/images/thuongthuongtotinh.jpeg",
    content: "Sang xịn mịn",
    hag_tag: "#gill #xuhuong #viral #thuongthichtotinh",
    music: "nhạc nền - ở đây chỉ có Rap 🎧",
    video: "/public/videos/gill.mp4",
    likes: "8571",
    comments: "21",
    shares: "30",
  },
  {
    id: 18,
    nick_name: "bapofficial.vn",
    full_name: "BAP Remix",
    avatar: "../public/images/bapofficial.vn.jpeg",
    content: "way back home lời việt",
    hag_tag: "#bigartsentertainment #bapremix #music #cover #nhachaymoingay",
    music: "nhạc nền - BAP Remix",
    video: "/public/videos/wbh.mp4",
    likes: "21.1K",
    comments: "31",
    shares: "77",
  },
  {
    id: 19,
    nick_name: "nghelaphe_music01",
    full_name: "Nghe Là Phê !",
    avatar: "../public/images/nghelaphe_music01.jpeg",
    content:
      "Bài hát có giai điệu cực hay nhưng không phải ai cũng hiểu ý nghĩa...",
    hag_tag:
      "#nhachaymoingay #batnhipcamxuc #nghelaphe #nguoidibao #lowg #cover #music",
    music: "nhạc nền - Nguyễn Hùng ⚜️",
    video: "/public/videos/heygirl.mp4",
    likes: "12.5K",
    comments: "103",
    shares: "65",
  },
  {
    id: 20,
    nick_name: "meaningful_english",
    full_name: "Enjoy learning English",
    avatar: "../public/images/meaningful_english.jpeg",
    content: "I do | 911 ft Duc Phuc.",
    hag_tag:
      " #learnontiktok #learnenglish #tienganh #hoctienganh #hoccungtiktok #fyp #trend #xuhuong #lyrics #vietsub #meaningful #love",
    music: "original sound - Enjoy learning English",
    video: "/public/videos/ido.mp4",
    likes: "73.5K",
    comments: "742",
    shares: "2029",
  },
  {
    id: 21,
    nick_name: "super.beo",
    full_name: "Phạm Tống Khang",
    avatar: "../public/images/super.beo.jpeg",
    content: "@Nếu không anh thì em có buồn ? ",
    hag_tag: "@#khangtong #cover #codontrensofa",
    music: "nhạc nền - Phạm Tống Khang",
    video: "/public/videos/sofa.mp4",
    likes: "49.5K",
    comments: "502",
    shares: "100",
  },
  {
    id: 22,
    nick_name: "han.lua",
    full_name: "𝗚𝗶𝗮 𝗛𝗮̂𝗻 🐰",
    avatar: "../public/images/han.lua",
    content: "Màu chím này chinh toá 🌷",
    hag_tag: "#viral #outfit #fyp",
    music: "nhạc nền - Lê Phương Trinh",
    video: "/public/videos/giahan.mp4",
    likes: "199",
    comments: "28",
    shares: "34",
  },
];
